
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ADJ Pro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="pt-PT">
      <body className={inter.className}>
        <main className='bg-zinc-100 h-screen'>
            {children}
        </main>
      </body>
    </html>
  )
}
